### ISSUE TITLE
animate all images in buffer? 

### ISSUE THREAD

**Issue by emacsomancer** [shg/org-inline-anim.el#1]
Is there an easy way of animating all animateable images in a buffer?

**Comment by shg** [comment]
Not possible with the current version of org-inline-anim.el but technically it's possible, by just calling `image-animate` on all the animatable images in the buffer at once.

I would like to implement it. But please be patient until I have some time for it. Thank you for your suggestion.

**Comment by emacsomancer** [comment]
Yes, of course, not a pressing issue, but would be nice to have eventually.

I note too that as-is this package already works also for WebP animated images, as supported by Emacs 29+ (cf. https://lars.ingebrigtsen.no/2022/04/13/15x10/ ), which is nice.

**Comment by shg** [comment]
> as-is this package already works also for WebP animated images

That's great to know!

;; Well, actually, this package doesn't do anything file-format specific, so I can say it is to be expected, but it is great to have an extra selling point without having done anything. :)

**Comment by shg** [comment]
Implemented in 9316fe78319fa18c7282993bd547cd33fda1b8ee

**Comment by emacsomancer** [comment]
`image-animate-loop` doesn't seem to be respected (never animates in loop)?

**Comment by shg** [comment]
This package does not check the `image-animate-loop` variable. You need to use the prefix argument to control looping etc. Are there any situations you want to use `image-animate-loop`?

**Comment by emacsomancer** [comment]
I think generally when I have images that can be animated visible, I want them to loop. I don't know if it would make sense to have a variable (either internal to `org-inline-anim` or re-using `image-animate-loop`) to enable this (without using the prefix argument).

**Comment by shg** [comment]
I see. It may be useful to allow a user to choose the default behavior. I think it's better to have an variable in `org-inline-anim` instead of reusing `image-animate-loop`. Let me think about it.
